### ISSUE TITLE
Rename to at_host-hex

### ISSUE THREAD

**Issue by coderbyheart** [NordicSemiconductor/at_host-hex#3]
See https://github.com/nrfconnect/sdk-nrf/pull/4407

**Comment by martiles** [comment]
_FYI.
https://github.com/nrfconnect/sdk-nrf/commit/03976752b5bcddca863f73b3ef8b7ada37563249_

saw your commit now :D
https://github.com/NordicSemiconductor/at_host-hex/commit/08bb4e0f9fe3356fbb9e5f306d171e1cc3484ae5

**Comment by coderbyheart** [comment]
Yeah, I'd like to keep the *AT host* name for this repo.
"AT Client" is the wrong name for the sample (however it is kept for historical reasons in NCS). The sample runs an AT command host, not a client, therefore *AT host* uses the correct name.
